site_name: UkoreInHouse
site_url: https://tonmaiart.github.io/UkoreInHouse/
repo_url: https://github.com/tonmaiart/UkoreInHouse
repo_name: tonmaiart/UkoreInHouse

theme:
  name: readthedocs
  language: en
  highlightjs: true

nav:
  - Introduction: intro.md
  - Pipeline Tools:
      - Ukore Hub:
          - Quick Start: ukore-hub/quick-start.md
          - Project Editor : ukore-hub/project-editor.md
          - Explorer : ukore-hub/explorer.md
          - Submit : ukore-hub/submit.md
          - Program Launcher : ukore-hub/program-launcher.md
      - Ukore Shot:
          - Quick Start: ukore-shot/quick-start.md
          - Comment Editor: ukore-shot/comment-editor.md

  - Projects:
      - Merdera Project:
        - Quick Start: merdera-project/quick_start.md
        - Pipeline: merdera-project/pipeline.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
