site_name: UkoreInHouse
site_url: https://tonmaiart.github.io/UkoreInHouse/
repo_url: https://github.com/tonmaiart/UkoreInHouse
repo_name: tonmaiart/UkoreInHouse

theme:
  name: readthedocs
  language: en
  highlightjs: true

nav:
  - Introduction: intro.md

  - Projects:
    - Merdera Project:
      - Introduction : merdera-project/quick_start.md
      - Production Pipeline:
            - Pipeline Overview: merdera-project/pipeline.md
            - Why Unity : merdera-project/unity-overview.md
      - Lookdev:
            - Lookdev Overview: merdera-project/lookdev.md

  - Pipeline Tools:
      - Ukore Hub:
          - Ukore Hub: ukore-hub/quick-start.md
          - Plugins - Ukore Shot: ukore-shot/quick-start.md
          
      - Unity Plugins:
          - Unity Ukore Importer: unity_ukore_importer/quick-start.md
          - Unity Ukore Toon Shader: unity_ukore_toonshader/quick-start.md

      - Maya Plugins:
          - Maya Publisher: maya-publisher/quick-start.md



markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
